import type { Metadata } from "next";
import { Inter, Varela_Round } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const varelaRound = Varela_Round({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={varelaRound.className + ` h-dvh w-dvh overflow-hidden`}>
        {children}
      </body>
    </html>
  );
}
